//! Integration tests for the Ses Dikte pipeline.
//!
//! These run the REAL bundled FFmpeg/ffprobe and (where noted) the REAL
//! whisper.cpp + model against synthetic fixtures generated by
//! `scripts/generate-speech-fixtures.ps1`. They skip with a visible message
//! when the engines or fixtures are not staged on the machine; set
//! `MEB_REQUIRE_SPEECH_ENGINES=1` to turn a skip into a failure (used for the
//! acceptance run).

use super::job::JobRegistry;
use super::limits::{SpeechLimits, DEFAULT_LIMITS};
use super::pipeline::{self, JobState};
use crate::engines::audio_prep;
use crate::engines::speech::{Segment, SpeechEngine, SpeechEngineInfo, TranscribeRequest, Transcript, WhisperCppEngine};
use crate::engines::speech_error::{SpeechError, SpeechErrorCode};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};

// ---------------------------------------------------------------- helpers ----

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/speech/generated")
}

fn require() -> bool {
    std::env::var("MEB_REQUIRE_SPEECH_ENGINES").map(|v| v == "1").unwrap_or(false)
}

/// Some(path) when the fixture exists; otherwise skip (or fail when required).
fn fixture(name: &str) -> Option<PathBuf> {
    let p = fixtures_dir().join(name);
    if p.is_file() {
        return Some(p);
    }
    assert!(!require(), "required fixture missing: {name} (run scripts/generate-speech-fixtures.ps1)");
    eprintln!("SKIP: fixture {name} not generated");
    None
}

fn audio_prep_ready() -> bool {
    let ok = audio_prep::status().is_ok();
    assert!(ok || !require(), "audio prep engine not staged/valid");
    if !ok {
        eprintln!("SKIP: bundled FFmpeg not staged");
    }
    ok
}

fn whisper_ready() -> Option<WhisperCppEngine> {
    match WhisperCppEngine::load() {
        Ok(e) => Some(e),
        Err(e) => {
            assert!(!require(), "speech engine not usable: {e}");
            eprintln!("SKIP: speech engine not usable: {}", e.code.as_str());
            None
        }
    }
}

/// Records what the pipeline handed to the engine, so tests can assert on the
/// preprocessed audio and on cleanup without running Whisper.
#[derive(Default)]
struct FakeEngine {
    calls: AtomicUsize,
    seen_job_dirs: Mutex<Vec<PathBuf>>,
    seen_wav_secs: Mutex<Vec<f64>>,
    normalized_ok: Mutex<Vec<bool>>,
    fail_first_n: AtomicUsize,
    delay_ms: u64,
}

impl SpeechEngine for FakeEngine {
    fn info(&self) -> SpeechEngineInfo {
        SpeechEngineInfo {
            engine_name: "fake".into(),
            engine_version: "0".into(),
            model_id: "fake".into(),
            languages: vec!["tr".into(), "auto".into()],
            supports_timestamps: true,
            supports_progress: false,
        }
    }
    fn transcribe(
        &self,
        req: &TranscribeRequest<'_>,
        cancel: &AtomicBool,
        _p: &(dyn Fn(Option<u8>) + Sync),
    ) -> Result<Transcript, SpeechError> {
        self.calls.fetch_add(1, Ordering::SeqCst);
        self.seen_job_dirs.lock().unwrap().push(req.job_dir.to_path_buf());
        let wav = req.job_dir.join(req.wav_name);
        let info = crate::engines::audio_wav::read_wav_info(&wav);
        self.normalized_ok.lock().unwrap().push(info.map(|i| i.is_speech_normalized()).unwrap_or(false));
        self.seen_wav_secs.lock().unwrap().push(info.map(|i| i.duration_secs()).unwrap_or(0.0));
        if self.delay_ms > 0 {
            let steps = self.delay_ms / 20;
            for _ in 0..steps {
                if cancel.load(Ordering::SeqCst) {
                    return Err(SpeechError::new(SpeechErrorCode::SpeechCancelled));
                }
                std::thread::sleep(std::time::Duration::from_millis(20));
            }
        }
        if self.fail_first_n.load(Ordering::SeqCst) > 0 {
            self.fail_first_n.fetch_sub(1, Ordering::SeqCst);
            return Err(SpeechError::new(SpeechErrorCode::SpeechTranscriptionFailed).with_detail("simulated failure"));
        }
        Ok(Transcript {
            language: req.language.to_string(),
            segments: vec![Segment { start_ms: 0, end_ms: 1000, text: "Merhaba dünya.".into() }],
            timestamps_available: true,
        })
    }
}

fn run(path: &Path, lang: &str, engine: &dyn SpeechEngine) -> Result<Transcript, SpeechError> {
    run_with(path, lang, &DEFAULT_LIMITS, engine, &AtomicBool::new(false))
}

fn run_with(
    path: &Path,
    lang: &str,
    limits: &SpeechLimits,
    engine: &dyn SpeechEngine,
    cancel: &AtomicBool,
) -> Result<Transcript, SpeechError> {
    pipeline::run_file_job(&path.to_string_lossy(), lang, limits, engine, cancel, &|_, _| {})
}

fn norm(s: &str) -> String {
    s.to_lowercase()
        .chars()
        .map(|c| match c {
            'ı' => 'i',
            'ş' => 's',
            'ğ' => 'g',
            'ü' => 'u',
            'ö' => 'o',
            'ç' => 'c',
            c if c.is_alphanumeric() || c == ' ' => c,
            _ => ' ',
        })
        .collect()
}

/// Real-Whisper tests are CPU-heavy and (for the cancel test) count OS processes,
/// so they must not overlap each other.
static REAL_WHISPER: Mutex<()> = Mutex::new(());
fn real_lock() -> std::sync::MutexGuard<'static, ()> {
    REAL_WHISPER.lock().unwrap_or_else(|e| e.into_inner())
}

fn tmp_dir() -> PathBuf {
    let d = std::env::temp_dir().join(format!("meb_speech_it_{}", uuid::Uuid::new_v4()));
    std::fs::create_dir_all(&d).unwrap();
    d
}

fn whisper_processes() -> usize {
    let out = std::process::Command::new("tasklist")
        .args(["/FI", "IMAGENAME eq whisper-cli.exe", "/NH"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).to_string())
        .unwrap_or_default();
    out.matches("whisper-cli.exe").count()
}

// ------------------------------------------------- formats (real FFmpeg) ----

#[test]
fn every_accepted_format_preprocesses_to_normalized_wav_with_a_real_fixture() {
    if !audio_prep_ready() {
        return;
    }
    // Extension -> fixture. An extension is only "supported" because its row
    // here passes; audio_prep::ACCEPTED_EXTENSIONS must equal this list.
    let table = [
        ("wav", "tr_speech.wav"),
        ("mp3", "tr_speech.mp3"),
        ("m4a", "tr_speech.m4a"),
        ("aac", "tr_speech.aac"),
        ("flac", "tr_speech.flac"),
        ("ogg", "tr_speech.ogg"),
        ("ogg", "tr_speech_opus.ogg"), // Ogg container with Opus, the other common .ogg
    ];
    let mut covered: Vec<&str> = table.iter().map(|(e, _)| *e).collect();
    covered.sort();
    covered.dedup();
    let mut accepted: Vec<&str> = audio_prep::ACCEPTED_EXTENSIONS.to_vec();
    accepted.sort();
    assert_eq!(covered, accepted, "every accepted extension needs a passing fixture (and vice versa)");

    for (ext, name) in table {
        let Some(path) = fixture(name) else { return };
        let engine = FakeEngine::default();
        let t = run(&path, "tr", &engine).unwrap_or_else(|e| panic!("{name} ({ext}) failed: {e}"));
        assert_eq!(t.segments.len(), 1);
        assert_eq!(engine.normalized_ok.lock().unwrap().as_slice(), &[true], "{name}: not 16k mono PCM16");
        let secs = engine.seen_wav_secs.lock().unwrap()[0];
        assert!((8.0..=16.0).contains(&secs), "{name}: implausible duration {secs}s (source is ~10s of speech)");
    }
}

#[test]
fn source_with_unicode_spaces_and_shell_metacharacters_in_its_name_is_handled_as_data() {
    if !audio_prep_ready() {
        return;
    }
    let Some(src) = fixture("tr_speech.mp3") else { return };
    let d = tmp_dir();
    let evil = d.join("toplantı kaydı & (özel) ; 'x' $HOME `id` %PATH% ş.mp3");
    std::fs::copy(&src, &evil).unwrap();
    let engine = FakeEngine::default();
    run(&evil, "tr", &engine).expect("metacharacters/Unicode in the file name must be inert");
    assert_eq!(engine.calls.load(Ordering::SeqCst), 1);
    let _ = std::fs::remove_dir_all(d);
}

// ------------------------------------------------------------ bad inputs ----

#[test]
fn zero_byte_file_is_rejected_before_any_process() {
    let d = tmp_dir();
    let p = d.join("empty.mp3");
    std::fs::write(&p, b"").unwrap();
    let engine = FakeEngine::default();
    let e = run(&p, "tr", &engine).unwrap_err();
    assert_eq!(e.code, SpeechErrorCode::SpeechInputUnsupported);
    assert!(e.message().contains("boş"));
    assert_eq!(engine.calls.load(Ordering::SeqCst), 0);
    let _ = std::fs::remove_dir_all(d);
}

#[test]
fn unsupported_extensions_are_rejected_without_opening_the_file() {
    let d = tmp_dir();
    for name in ["notes.txt", "clip.mp4", "clip.wma", "clip.opus", "tool.exe", "song.mp3.exe", "noext"] {
        let p = d.join(name);
        std::fs::write(&p, b"RIFF....WAVE").unwrap();
        let engine = FakeEngine::default();
        let e = run(&p, "tr", &engine).unwrap_err();
        assert_eq!(e.code, SpeechErrorCode::SpeechInputUnsupported, "{name}");
        assert!(e.message().contains("WAV, MP3, M4A, AAC, FLAC, OGG"));
        assert_eq!(engine.calls.load(Ordering::SeqCst), 0);
    }
    let _ = std::fs::remove_dir_all(d);
}

#[test]
fn remote_urls_and_unc_paths_are_never_accepted() {
    let engine = FakeEngine::default();
    for bad in [
        "http://example.com/a.mp3",
        "https://example.com/a.wav",
        "ftp://x/a.mp3",
        "rtmp://x/a.flac",
        "\\\\server\\share\\a.mp3",
        "//server/share/a.mp3",
        "file:///C:/a.mp3",
    ] {
        let e = pipeline::run_file_job(bad, "tr", &DEFAULT_LIMITS, &engine, &AtomicBool::new(false), &|_, _| {}).unwrap_err();
        assert_eq!(e.code, SpeechErrorCode::SpeechInputUnsupported, "{bad}");
    }
    assert_eq!(engine.calls.load(Ordering::SeqCst), 0);
}

#[test]
fn missing_file_is_reported_as_not_found_in_turkish() {
    let engine = FakeEngine::default();
    let e = run(Path::new("C:\\definitely\\not\\here\\a.mp3"), "tr", &engine).unwrap_err();
    assert_eq!(e.code, SpeechErrorCode::SpeechInputNotFound);
    assert!(e.message().contains("erişilemiyor"));
}

#[test]
fn corrupt_mp3_fails_with_a_structured_turkish_error_and_leaves_no_temp_files() {
    if !audio_prep_ready() {
        return;
    }
    let d = tmp_dir();
    let p = d.join("corrupt.mp3");
    // pseudo-random garbage with an ID3 header so it "looks like" an MP3
    let mut junk = b"ID3\x03\x00\x00\x00\x00\x00\x00".to_vec();
    let mut x: u32 = 0x1234_5678;
    for _ in 0..40_000 {
        x = x.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
        junk.push((x >> 24) as u8);
    }
    std::fs::write(&p, junk).unwrap();
    let engine = FakeEngine::default();
    let e = run(&p, "tr", &engine).unwrap_err();
    assert!(
        matches!(e.code, SpeechErrorCode::SpeechPreprocessFailed | SpeechErrorCode::SpeechInputUnsupported),
        "unexpected code {:?}",
        e.code
    );
    assert!(e.message().ends_with('.'));
    assert!(!e.message().to_lowercase().contains("ffmpeg"));
    assert_eq!(engine.calls.load(Ordering::SeqCst), 0);
    let _ = std::fs::remove_dir_all(d);
}

#[test]
fn truncated_real_mp3_is_handled_without_crashing() {
    if !audio_prep_ready() {
        return;
    }
    let Some(src) = fixture("tr_speech.mp3") else { return };
    let d = tmp_dir();
    let p = d.join("truncated.mp3");
    let bytes = std::fs::read(&src).unwrap();
    std::fs::write(&p, &bytes[..bytes.len() / 3]).unwrap();
    let engine = FakeEngine::default();
    // Either a shorter decode succeeds or a structured error is returned; both are acceptable, a panic/hang is not.
    match run(&p, "tr", &engine) {
        Ok(_) => assert_eq!(engine.calls.load(Ordering::SeqCst), 1),
        Err(e) => assert!(matches!(e.code, SpeechErrorCode::SpeechPreprocessFailed | SpeechErrorCode::SpeechNoSpeechDetected)),
    }
    let _ = std::fs::remove_dir_all(d);
}

#[test]
fn valid_container_without_an_audio_stream_is_unsupported() {
    if !audio_prep_ready() {
        return;
    }
    let Some(p) = fixture("no_audio_stream.m4a") else { return };
    let engine = FakeEngine::default();
    let e = run(&p, "tr", &engine).unwrap_err();
    assert_eq!(e.code, SpeechErrorCode::SpeechInputUnsupported);
    assert!(e.message().contains("ses akışı"));
    assert_eq!(engine.calls.load(Ordering::SeqCst), 0);
}

// ----------------------------------------------------- silence / no speech ----

#[test]
fn silence_never_reaches_the_speech_engine() {
    if !audio_prep_ready() {
        return;
    }
    let Some(p) = fixture("silence.wav") else { return };
    let engine = FakeEngine::default();
    let e = run(&p, "tr", &engine).unwrap_err();
    assert_eq!(e.code, SpeechErrorCode::SpeechNoSpeechDetected);
    assert_eq!(e.message(), "Konuşma algılanamadı.");
    assert_eq!(engine.calls.load(Ordering::SeqCst), 0, "whisper must not be run on silence (it hallucinates)");
}

// -------------------------------------------------------------- limits ------

#[test]
fn oversized_input_is_rejected_gracefully_before_processing() {
    let Some(p) = fixture("tr_speech.wav") else { return };
    let tiny = SpeechLimits { max_input_bytes: 1000, ..DEFAULT_LIMITS };
    let engine = FakeEngine::default();
    let e = run_with(&p, "tr", &tiny, &engine, &AtomicBool::new(false)).unwrap_err();
    assert_eq!(e.code, SpeechErrorCode::SpeechResourceLimit);
    assert!(e.message().contains("çok büyük"));
    assert_eq!(engine.calls.load(Ordering::SeqCst), 0);
}

#[test]
fn over_long_audio_is_rejected_using_probed_and_measured_duration() {
    if !audio_prep_ready() {
        return;
    }
    let short = SpeechLimits { max_audio_secs: 2, ..DEFAULT_LIMITS };
    // WAV states its duration -> caught at the probe stage.
    // ADTS AAC states none -> caught after normalization from the decoded samples.
    for name in ["tr_speech.wav", "tr_speech.aac", "tr_speech.mp3"] {
        let Some(p) = fixture(name) else { return };
        let engine = FakeEngine::default();
        let e = run_with(&p, "tr", &short, &engine, &AtomicBool::new(false)).unwrap_err();
        assert_eq!(e.code, SpeechErrorCode::SpeechResourceLimit, "{name}");
        assert!(e.message().contains("çok uzun"), "{name}");
        assert_eq!(engine.calls.load(Ordering::SeqCst), 0, "{name}");
    }
}

#[test]
fn the_duration_limit_boundary_accepts_exactly_the_limit_and_rejects_above() {
    // pure boundary check on the policy object (file-independent)
    let l = DEFAULT_LIMITS;
    assert!(l.check_duration(l.max_audio_secs as f64).is_ok());
    assert!(l.check_duration(l.max_audio_secs as f64 + 0.5).is_err());
}

#[test]
fn unsupported_language_is_refused() {
    let Some(p) = fixture("tr_speech.wav") else { return };
    let engine = FakeEngine::default();
    let e = run(&p, "en", &engine).unwrap_err();
    assert_eq!(e.code, SpeechErrorCode::SpeechLanguageUnsupported);
}

// ------------------------------------------------- state / no fake progress ----

#[test]
fn long_running_job_reports_states_but_never_invents_progress() {
    if !audio_prep_ready() {
        return;
    }
    let Some(p) = fixture("tr_speech.mp3") else { return };
    let engine = FakeEngine { delay_ms: 400, ..Default::default() };
    let events: Mutex<Vec<(JobState, Option<u8>)>> = Mutex::new(vec![]);
    let cancel = AtomicBool::new(false);
    pipeline::run_file_job(&p.to_string_lossy(), "tr", &DEFAULT_LIMITS, &engine, &cancel, &|s, pct| {
        events.lock().unwrap().push((s, pct));
    })
    .unwrap();
    let ev = events.lock().unwrap();
    assert_eq!(ev.first().unwrap().0, JobState::Preparing);
    assert!(ev.iter().any(|(s, _)| *s == JobState::Transcribing));
    // the fake engine reports no progress, so the pipeline must not either
    assert!(ev.iter().all(|(_, pct)| pct.is_none()), "pipeline fabricated progress: {:?}", *ev);
}

// ----------------------------------------------------- retry / no poisoning ----

#[test]
fn a_failed_job_frees_the_slot_and_a_retry_on_the_same_source_succeeds() {
    if !audio_prep_ready() {
        return;
    }
    let Some(p) = fixture("tr_speech.wav") else { return };
    let registry = Arc::new(JobRegistry::default());
    let engine = FakeEngine { fail_first_n: AtomicUsize::new(1), ..Default::default() };

    let slot = registry.try_begin().unwrap();
    let err = run_with(&p, "tr", &DEFAULT_LIMITS, &engine, &slot.cancel).unwrap_err();
    assert_eq!(err.code, SpeechErrorCode::SpeechTranscriptionFailed);
    drop(slot);

    // same source, fresh job: works, and the earlier failure left nothing behind
    let slot2 = registry.try_begin().expect("slot must be free after a failure");
    let ok = run_with(&p, "tr", &DEFAULT_LIMITS, &engine, &slot2.cancel);
    assert!(ok.is_ok());
    assert_eq!(engine.calls.load(Ordering::SeqCst), 2);
    for dir in engine.seen_job_dirs.lock().unwrap().iter() {
        assert!(!dir.exists(), "job dir leaked: {:?}", dir);
    }
}

// -------------------------------------------------------- temp cleanup ------

#[test]
fn job_directories_are_removed_on_success_failure_and_cancel() {
    if !audio_prep_ready() {
        return;
    }
    let Some(p) = fixture("tr_speech.wav") else { return };
    let engine = FakeEngine::default();
    run(&p, "tr", &engine).unwrap(); // success
    engine.fail_first_n.store(1, Ordering::SeqCst);
    let _ = run(&p, "tr", &engine).unwrap_err(); // failure inside the engine
    let cancelled = AtomicBool::new(true);
    let _ = run_with(&p, "tr", &DEFAULT_LIMITS, &engine, &cancelled).unwrap_err(); // cancelled up front
    let dirs = engine.seen_job_dirs.lock().unwrap();
    assert!(dirs.len() >= 2);
    for d in dirs.iter() {
        assert!(!d.exists(), "leaked job dir {:?}", d);
    }
}

// ------------------------------------------------------ cancellation -------

#[test]
fn cancel_kills_a_running_process_promptly_and_reports_cancelled() {
    use crate::engines::engine_id::EngineId;
    use crate::engines::process::{run_cancellable, CancellableRun, ProcessEnd};
    use crate::engines::resolver::{EngineTier, ResolvedEngine};
    // `ping` stands in for any long-running child (present on every Windows install).
    let resolved = ResolvedEngine { id: EngineId::Speech, path: PathBuf::from("ping"), tier: EngineTier::System };
    let cancel = AtomicBool::new(false);
    let started = std::time::Instant::now();
    let res = std::thread::scope(|s| {
        s.spawn(|| {
            std::thread::sleep(std::time::Duration::from_millis(300));
            cancel.store(true, Ordering::SeqCst);
        });
        run_cancellable(
            &resolved,
            &["127.0.0.1".into(), "-n".into(), "60".into()],
            &std::env::temp_dir(),
            CancellableRun { timeout: None, cancel: &cancel, low_priority: false, on_stderr_line: None },
        )
    });
    assert_eq!(res.end, ProcessEnd::Cancelled);
    assert!(started.elapsed() < std::time::Duration::from_secs(5), "cancel took {:?}", started.elapsed());
}

#[test]
fn cancel_during_normalization_stops_ffmpeg_and_cleans_up() {
    if !audio_prep_ready() {
        return;
    }
    // ~1 GB of 44.1 kHz stereo silence-with-tone: long enough that decoding is still
    // running when the cancel arrives. Limits are widened so it is not rejected up front.
    let d = tmp_dir();
    let big = d.join("big.wav");
    {
        use std::io::Write;
        let secs: u64 = 6000; // 100 minutes
        let data_len = secs * 44_100 * 4;
        let mut f = std::io::BufWriter::new(std::fs::File::create(&big).unwrap());
        f.write_all(b"RIFF").unwrap();
        f.write_all(&((36 + data_len) as u32).to_le_bytes()).unwrap();
        f.write_all(b"WAVEfmt ").unwrap();
        f.write_all(&16u32.to_le_bytes()).unwrap();
        f.write_all(&1u16.to_le_bytes()).unwrap();
        f.write_all(&2u16.to_le_bytes()).unwrap();
        f.write_all(&44_100u32.to_le_bytes()).unwrap();
        f.write_all(&(44_100u32 * 4).to_le_bytes()).unwrap();
        f.write_all(&4u16.to_le_bytes()).unwrap();
        f.write_all(&16u16.to_le_bytes()).unwrap();
        f.write_all(b"data").unwrap();
        f.write_all(&(data_len as u32).to_le_bytes()).unwrap();
        let block = vec![7u8; 44_100 * 4]; // 1 s
        for _ in 0..secs {
            f.write_all(&block).unwrap();
        }
    }
    let wide = SpeechLimits { max_input_bytes: 2_000_000_000, max_audio_secs: 10 * 3600, ..DEFAULT_LIMITS };
    let engine = FakeEngine::default();
    let cancel = AtomicBool::new(false);
    let started = std::time::Instant::now();
    let res = std::thread::scope(|s| {
        s.spawn(|| {
            std::thread::sleep(std::time::Duration::from_millis(400));
            cancel.store(true, Ordering::SeqCst);
        });
        run_with(&big, "tr", &wide, &engine, &cancel)
    });
    let e = res.unwrap_err();
    assert_eq!(e.code, SpeechErrorCode::SpeechCancelled);
    assert_eq!(engine.calls.load(Ordering::SeqCst), 0, "engine must not run after a cancelled normalization");
    assert!(started.elapsed() < std::time::Duration::from_secs(20), "cancel too slow: {:?}", started.elapsed());
    let _ = std::fs::remove_dir_all(d);
}

// ------------------------------------------- real Whisper (Turkish, etc.) ----

#[test]
fn real_turkish_transcription_from_wav_and_mp3() {
    let _serial = real_lock();
    if !audio_prep_ready() {
        return;
    }
    let Some(engine) = whisper_ready() else { return };
    for name in ["tr_speech.wav", "tr_speech.mp3"] {
        let Some(p) = fixture(name) else { return };
        let started = std::time::Instant::now();
        let t = run(&p, "tr", &engine).unwrap_or_else(|e| panic!("{name}: {e}"));
        let text = t.plain_text();
        eprintln!("[{name}] {:?} in {:.1}s -> {text}", t.language, started.elapsed().as_secs_f64());
        // The fixture is *synthetic* TTS, so this is a pipeline smoke test, NOT an accuracy benchmark
        // (real-speech accuracy is measured by `measure_word_error_rate_on_human_speech_when_provided`).
        let n = norm(&text);
        let hits = ["merhaba", "siber", "verilerini", "korumak", "yeni", "maddesi"].iter().filter(|w| n.contains(**w)).count();
        assert!(hits >= 3, "{name}: only {hits}/6 expected words recognised in '{n}'");
        assert_eq!(t.language, "tr");
        assert!(t.timestamps_available);
        assert!(t.segments.iter().all(|s| s.end_ms >= s.start_ms));
    }
}

#[test]
fn real_auto_language_detects_turkish() {
    let _serial = real_lock();
    if !audio_prep_ready() {
        return;
    }
    let Some(engine) = whisper_ready() else { return };
    let Some(p) = fixture("tr_speech.flac") else { return };
    let t = run(&p, "auto", &engine).unwrap();
    eprintln!("[auto] language={} text={}", t.language, t.plain_text());
    assert_eq!(t.language, "tr");
}

#[test]
fn real_music_like_audio_does_not_produce_a_fake_successful_transcript() {
    let _serial = real_lock();
    if !audio_prep_ready() {
        return;
    }
    let Some(engine) = whisper_ready() else { return };
    let Some(p) = fixture("music_like.wav") else { return };
    match run(&p, "tr", &engine) {
        Err(e) => {
            eprintln!("[music] -> {}", e.code.as_str());
            assert_eq!(e.code, SpeechErrorCode::SpeechNoSpeechDetected);
        }
        Ok(t) => {
            // Whisper may still emit a little text over tones; it must be short, not a fabricated
            // paragraph, and never a known subtitle-credit hallucination like "Altyazı M.K.".
            let text = t.plain_text();
            let words = text.split_whitespace().count();
            eprintln!("[music] produced {words} words: {text}");
            assert!(words <= 6, "music-only input produced a long transcript: {text}");
            assert!(!norm(&text).contains("altyazi"), "subtitle-credit hallucination leaked: {text}");
        }
    }
}

#[test]
fn real_cancel_during_transcription_kills_whisper_and_cleans_up() {
    let _serial = real_lock();
    if !audio_prep_ready() {
        return;
    }
    let Some(engine) = whisper_ready() else { return };
    let Some(p) = fixture("tr_speech_long.wav") else { return };
    let before = whisper_processes();
    let cancel = AtomicBool::new(false);
    let seen_transcribing = AtomicBool::new(false);
    let started = std::time::Instant::now();
    let res = std::thread::scope(|s| {
        s.spawn(|| {
            // wait until transcription really started, then let it run briefly
            while !seen_transcribing.load(Ordering::SeqCst) {
                std::thread::sleep(std::time::Duration::from_millis(50));
                if started.elapsed().as_secs() > 60 {
                    break;
                }
            }
            std::thread::sleep(std::time::Duration::from_secs(4));
            cancel.store(true, Ordering::SeqCst);
        });
        pipeline::run_file_job(&p.to_string_lossy(), "tr", &DEFAULT_LIMITS, &engine, &cancel, &|s, _| {
            if s == JobState::Transcribing {
                seen_transcribing.store(true, Ordering::SeqCst);
            }
        })
    });
    let e = res.unwrap_err();
    assert_eq!(e.code, SpeechErrorCode::SpeechCancelled);
    let mut after = whisper_processes();
    for _ in 0..30 {
        if after <= before {
            break;
        }
        std::thread::sleep(std::time::Duration::from_millis(100));
        after = whisper_processes();
    }
    assert!(after <= before, "a whisper-cli process is still running after cancel ({after} > {before})");
    eprintln!("[cancel] cancelled after {:.1}s total", started.elapsed().as_secs_f64());
}

#[test]
fn real_long_audio_ten_minutes_transcribes_without_blocking() {
    let _serial = real_lock();
    if std::env::var("MEB_RUN_LONG_SPEECH_TEST").map(|v| v != "1").unwrap_or(true) {
        eprintln!("SKIP: long test (set MEB_RUN_LONG_SPEECH_TEST=1)");
        return;
    }
    if !audio_prep_ready() {
        return;
    }
    let Some(engine) = whisper_ready() else { return };
    let Some(p) = fixture("tr_speech_long.wav") else { return };
    let last_pct = Mutex::new(None::<u8>);
    let started = std::time::Instant::now();
    let t = pipeline::run_file_job(&p.to_string_lossy(), "tr", &DEFAULT_LIMITS, &engine, &AtomicBool::new(false), &|_, pct| {
        if pct.is_some() {
            *last_pct.lock().unwrap() = pct;
        }
    })
    .unwrap();
    let secs = started.elapsed().as_secs_f64();
    let words = t.plain_text().split_whitespace().count();
    eprintln!("[long] {} segments, {words} words in {secs:.0}s; last progress {:?}", t.segments.len(), last_pct.lock().unwrap());
    assert!(t.segments.len() > 20);
    assert!(norm(&t.plain_text()).contains("siber"));
}

// --------------------------------------------------------- audits ----------

#[test]
fn whisper_argv_is_structured_local_and_contains_no_shell_or_url() {
    let Some(engine) = whisper_ready() else { return };
    let d = tmp_dir();
    let req = TranscribeRequest { job_dir: &d, wav_name: "norm.wav", language: "tr" };
    let args = engine.build_args(&req, "m/ggml-x.bin", "transcript");
    for a in &args {
        let l = a.to_lowercase();
        assert!(!l.contains("://") && !l.contains("http"), "URL-ish arg: {a}");
        assert!(!["cmd", "cmd.exe", "powershell", "sh", "bash", "/c", "-command"].contains(&l.as_str()), "shell arg: {a}");
    }
    assert!(args.windows(2).any(|w| w[0] == "-f" && w[1] == "norm.wav"), "input must be the generated relative name");
    assert!(args.windows(2).any(|w| w[0] == "-l" && w[1] == "tr"));
    assert!(args.contains(&"-ng".to_string()), "GPU backends must stay off");
    let m = args.windows(2).find(|w| w[0] == "-m").map(|w| w[1].clone()).unwrap();
    assert_eq!(m, "m/ggml-x.bin", "the model argument is exactly what the caller exposed");
    assert!(args.iter().all(|a| a.is_ascii()), "every argument handed to whisper must be ASCII");
    let _ = std::fs::remove_dir_all(d);
}

#[test]
fn no_network_client_exists_in_dependencies_or_speech_sources() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    // Both manifests on the speech path: this crate, and the shared
    // `meb-engines` crate that now holds the engine resolver, the process
    // runner and the bundle verifier.
    for manifest in ["Cargo.toml", "../crates/meb-engines/Cargo.toml"] {
        let cargo = std::fs::read_to_string(root.join(manifest)).unwrap().to_lowercase();
        // Only real dependency lines count: Cargo.toml's comments legitimately *mention* removed crates.
        let deps: String = cargo
            .split("[dependencies]")
            .nth(1)
            .unwrap_or("")
            .split("\n[")
            .next()
            .unwrap_or("")
            .lines()
            .map(|l| l.split('#').next().unwrap_or(""))
            .collect::<Vec<_>>()
            .join("\n");
        for banned in ["reqwest", "hyper", "ureq", "isahc", "attohttpc", "surf", "curl", "tungstenite", "websocket", "tokio-tungstenite", "native-tls", "openssl", "rustls"] {
            assert!(!deps.contains(banned), "network-capable crate in {manifest}: {banned}");
        }
    }
    let files = [
        "src/speech/commands.rs",
        "src/speech/job.rs",
        "src/speech/limits.rs",
        "src/speech/pipeline.rs",
        "src/engines/speech.rs",
        "src/engines/speech_manifest.rs",
        "src/engines/audio_prep.rs",
        "src/engines/audio_wav.rs",
        "src/engines/ffmpeg_manifest.rs",
        "src/engines/resolver.rs",
        // Moved into the shared `meb-engines` crate, still squarely on the
        // speech path: the bundle verifier, the engine identity/error model,
        // the resolution mechanism, and the process runner that is what
        // actually spawns whisper.cpp.
        "../crates/meb-engines/src/bundle.rs",
        "../crates/meb-engines/src/engine_id.rs",
        "../crates/meb-engines/src/error.rs",
        "../crates/meb-engines/src/process.rs",
        "../crates/meb-engines/src/resolver.rs",
    ];
    for f in files {
        let src = std::fs::read_to_string(root.join(f)).unwrap();
        // strip the test module so test fixtures/URLs in string literals don't count
        let prod = src.split("#[cfg(test)]").next().unwrap();
        for banned in ["TcpStream", "UdpSocket", "std::net", "reqwest", "hyper::", "http://", "https://"] {
            assert!(!prod.contains(banned), "{f} contains network-capable code/URL: {banned}");
        }
    }
}

#[test]
fn ffmpeg_argv_locks_the_file_protocol_and_bounds_output() {
    // Static audit of the preprocessing invocation (the source of truth for what runs).
    let src = include_str!("../engines/audio_prep.rs");
    let prod = src.split("#[cfg(test)]").next().unwrap();
    for needle in ["\"-protocol_whitelist\", \"file\"", "spec_rel(", "spec_abs(", "\"-map\", \"0:a:0\"", "\"-vn\"", "\"-nostdin\"", "\"-t\""] {
        assert!(prod.contains(needle), "missing hardening: {needle}");
    }
    assert!(!prod.contains("Command::new(\"cmd") && !prod.contains("powershell"));
}

// ------------------------------------------- human-speech measurement ----------

fn word_error_rate(reference: &str, hypothesis: &str) -> f64 {
    let r: Vec<&str> = reference.split_whitespace().collect();
    let h: Vec<&str> = hypothesis.split_whitespace().collect();
    if r.is_empty() {
        return if h.is_empty() { 0.0 } else { 1.0 };
    }
    let mut prev: Vec<usize> = (0..=h.len()).collect();
    for i in 1..=r.len() {
        let mut cur = vec![i; h.len() + 1];
        for j in 1..=h.len() {
            let sub = prev[j - 1] + usize::from(r[i - 1] != h[j - 1]);
            cur[j] = sub.min(prev[j] + 1).min(cur[j - 1] + 1);
        }
        prev = cur;
    }
    prev[h.len()] as f64 / r.len() as f64
}

/// Measurement, not a pass/fail accuracy gate: point `MEB_HUMAN_SPEECH_DIR` at a folder of
/// `<name>.wav|mp3|...` + `<name>.txt` (reference) pairs. Not run by default.
#[test]
fn measure_word_error_rate_on_human_speech_when_provided() {
    let _serial = real_lock();
    let Ok(dir) = std::env::var("MEB_HUMAN_SPEECH_DIR") else {
        eprintln!("SKIP: set MEB_HUMAN_SPEECH_DIR to measure real-speech accuracy");
        return;
    };
    if !audio_prep_ready() {
        return;
    }
    let Some(engine) = whisper_ready() else { return };
    let mut total_ref = 0usize;
    let mut total_err = 0f64;
    let mut entries: Vec<PathBuf> = std::fs::read_dir(&dir).unwrap().flatten().map(|e| e.path()).collect();
    entries.sort();
    for p in entries {
        let ext = p.extension().and_then(|e| e.to_str()).unwrap_or("").to_lowercase();
        if audio_prep::ACCEPTED_EXTENSIONS.contains(&ext.as_str()) {
            let Ok(reference) = std::fs::read_to_string(p.with_extension("txt")) else { continue };
            let started = std::time::Instant::now();
            let t = run(&p, "tr", &engine).unwrap();
            let (r, h) = (norm(&reference), norm(&t.plain_text()));
            let wer = word_error_rate(&r, &h);
            eprintln!(
                "[{}] {:.1}s  WER={:.0}%\n  REF: {}\n  HYP: {}",
                p.file_name().unwrap().to_string_lossy(),
                started.elapsed().as_secs_f64(),
                wer * 100.0,
                reference.trim(),
                t.plain_text()
            );
            let n = r.split_whitespace().count();
            total_ref += n;
            total_err += wer * n as f64;
        }
    }
    if total_ref > 0 {
        eprintln!("[overall] word error rate (diacritics folded): {:.0}% over {total_ref} reference words", total_err / total_ref as f64 * 100.0);
    }
}

#[test]
fn word_error_rate_helper_is_correct() {
    assert_eq!(word_error_rate("a b c d", "a b c d"), 0.0);
    assert_eq!(word_error_rate("a b c d", "a x c d"), 0.25);
    assert_eq!(word_error_rate("a b c d", "a b"), 0.5);
    assert_eq!(word_error_rate("", ""), 0.0);
}

// ---------------------------------------- non-ASCII paths (end to end) ----------

/// Directory names in every script the app can meet on a Windows PC, incl. the
/// Turkish examples from the requirements (`Çalışmalar`, `Öğretmen`, `Kullanıcılar`).
fn unicode_dirs() -> Vec<&'static str> {
    let mut v = crate::engines::ascii_link::unicode_test_dir_names();
    v.extend(["Kullanıcılar", "Belgeler_Öğretmen", "Çalışmalar"]);
    v
}

#[test]
fn source_and_job_root_under_non_ascii_paths_work_for_every_script() {
    if !audio_prep_ready() {
        return;
    }
    let Some(src) = fixture("tr_speech.mp3") else { return };
    for name in unicode_dirs() {
        let base = tmp_dir();
        let src_dir = base.join(name).join("Öğretmen ders kaydı");
        std::fs::create_dir_all(&src_dir).unwrap();
        let source = src_dir.join("ders kaydı ığşç İ.mp3");
        std::fs::copy(&src, &source).unwrap();
        let job_root = base.join(name).join("temp").join("speech");
        std::fs::create_dir_all(&job_root).unwrap();

        let engine = FakeEngine::default();
        pipeline::run_file_job_in(&job_root, &source.to_string_lossy(), "tr", &DEFAULT_LIMITS, &engine, &AtomicBool::new(false), &|_, _| {})
            .unwrap_or_else(|e| panic!("{name}: {e}"));
        assert_eq!(engine.normalized_ok.lock().unwrap().as_slice(), &[true], "{name}");
        // the user's file is untouched, and no job dir is left behind under the odd root
        assert!(source.is_file(), "{name}");
        assert_eq!(std::fs::read_dir(&job_root).unwrap().count(), 0, "{name}: job dir leaked");
        let _ = std::fs::remove_dir_all(base);
    }
}

/// Builds a copy of the staged engine under `root` (bin copied, model hard-linked, manifest copied).
fn engine_copy_under(root: &Path) -> Option<PathBuf> {
    use crate::engines::{engine_id::EngineId, resolver, speech_manifest};
    let src = resolver::bundled_engine_dir(EngineId::Speech)?;
    let m = speech_manifest::load_manifest(&src).ok()?;
    let dst = root.join("engines").join("speech");
    std::fs::create_dir_all(dst.join("bin")).ok()?;
    std::fs::create_dir_all(dst.join("models")).ok()?;
    std::fs::copy(src.join("manifest.json"), dst.join("manifest.json")).ok()?;
    for e in std::fs::read_dir(src.join("bin")).ok()? .flatten() {
        std::fs::copy(e.path(), dst.join("bin").join(e.file_name())).ok()?;
    }
    let rel = m.model.file_relative_path;
    std::fs::hard_link(src.join(&rel), dst.join(&rel)).or_else(|_| std::fs::copy(src.join(&rel), dst.join(&rel)).map(|_| ())).ok()?;
    Some(dst)
}

#[test]
fn real_whisper_gives_identical_output_from_engine_source_and_job_dirs_with_non_ascii_paths() {
    let _serial = real_lock();
    if !audio_prep_ready() {
        return;
    }
    let Some(baseline_engine) = whisper_ready() else { return };
    let Some(src) = fixture("tr_speech.mp3") else { return };

    // baseline: everything ASCII
    let baseline = run(&src, "tr", &baseline_engine).expect("baseline");
    eprintln!("[paths] baseline: {}", baseline.plain_text());

    for name in ["Çalışmalar", "Kullanıcılar", "Belgeler_Öğretmen_ğışİ", "Жук_Иван", "مجلد_عربي", "日本語_中文"] {
        let base = tmp_dir().join(name); // whole tree (engine, source, job root) below a non-ASCII dir
        std::fs::create_dir_all(&base).unwrap();
        let Some(engine_dir) = engine_copy_under(&base) else { return };
        let engine = WhisperCppEngine::load_from_dir(&engine_dir).unwrap_or_else(|e| panic!("{name}: {e}"));

        let src_dir = base.join("Öğretmen").join("Ses Kayıtları");
        std::fs::create_dir_all(&src_dir).unwrap();
        let source = src_dir.join("ders kaydı ığşç İ.mp3");
        std::fs::copy(&src, &source).unwrap();
        let job_root = base.join("temp").join("speech");
        std::fs::create_dir_all(&job_root).unwrap();

        let t = pipeline::run_file_job_in(&job_root, &source.to_string_lossy(), "tr", &DEFAULT_LIMITS, &engine, &AtomicBool::new(false), &|_, _| {})
            .unwrap_or_else(|e| panic!("{name}: transcription failed: {e}"));
        assert_eq!(t.plain_text(), baseline.plain_text(), "{name}: output differs from the ASCII-path baseline");
        assert_eq!(std::fs::read_dir(&job_root).unwrap().count(), 0, "{name}: job dir leaked");
        // cleanup never touched the engine's model behind the junction
        assert!(engine_dir.join("models").read_dir().unwrap().count() >= 1, "{name}: model gone");
        eprintln!("[paths] {name}: identical output, no leak");
        let _ = std::fs::remove_dir_all(base.parent().unwrap());
    }
}

// ------------------------------------------------------ model benchmark ---------

/// Benchmark runner, NOT a pass/fail test (skips unless configured). Runs the dataset in
/// `$MEB_BENCH_ROOT/dataset` (manifest.tsv: file \t category \t reference) through the REAL pipeline
/// with the engine directory `$MEB_BENCH_ROOT/engines/$MEB_BENCH_MODEL`, and writes one JSON line per
/// file to `$MEB_BENCH_ROOT/results/$MEB_BENCH_MODEL.jsonl`. Scoring is done by scripts/bench/bench_analyze.py.
#[test]
fn benchmark_model_when_configured() {
    let (Ok(root), Ok(model)) = (std::env::var("MEB_BENCH_ROOT"), std::env::var("MEB_BENCH_MODEL")) else {
        eprintln!("SKIP: set MEB_BENCH_ROOT and MEB_BENCH_MODEL to run the model benchmark");
        return;
    };
    let _serial = real_lock();
    let root = PathBuf::from(root);
    let engine = WhisperCppEngine::load_from_dir(&root.join("engines").join(&model)).expect("bench engine");
    let manifest = std::fs::read_to_string(root.join("dataset").join("manifest.tsv")).unwrap();
    std::fs::create_dir_all(root.join("results")).unwrap();
    let out_path = root.join("results").join(format!("{model}.jsonl"));
    let mut out = std::fs::File::create(&out_path).unwrap();
    // a whole 10 minute recording is legitimate input here
    let limits = SpeechLimits { max_audio_secs: 3 * 3600, ..DEFAULT_LIMITS };
    let only = std::env::var("MEB_BENCH_ONLY").ok(); // optional category filter (comma list)
    for line in manifest.lines() {
        let cols: Vec<&str> = line.splitn(3, '\t').collect();
        if cols.len() < 2 {
            continue;
        }
        let (file, category) = (cols[0], cols[1]);
        if let Some(o) = &only {
            if !o.split(',').any(|c| c == category) {
                continue;
            }
        }
        let path = root.join("dataset").join(file);
        let audio_s = crate::engines::audio_wav::read_wav_info(&path).map(|i| i.duration_secs()).unwrap_or(0.0);
        let started = std::time::Instant::now();
        let res = pipeline::run_file_job(&path.to_string_lossy(), "tr", &limits, &engine, &AtomicBool::new(false), &|_, _| {});
        let wall = started.elapsed().as_secs_f64();
        let rec = match res {
            Ok(t) => serde_json::json!({
                "file": file, "category": category, "audio_s": audio_s, "wall_s": wall, "ok": true,
                "text": t.plain_text(),
                "segments": t.segments.iter().map(|s| serde_json::json!({"s": s.start_ms, "e": s.end_ms, "t": s.text})).collect::<Vec<_>>(),
            }),
            Err(e) => serde_json::json!({
                "file": file, "category": category, "audio_s": audio_s, "wall_s": wall, "ok": false, "code": e.code.as_str(), "text": "",
            }),
        };
        use std::io::Write;
        writeln!(out, "{}", rec).unwrap();
        eprintln!("[bench {model}] {file:28} {category:12} audio {audio_s:6.1}s wall {wall:6.1}s ok={}", rec["ok"]);
    }
}
